app:
  resource: "@AppBundle/Controller/DefaultController.php"
  type:     annotation
  prefix:   /
printer:
  resource: "@AppBundle/Controller/PrinterController.php"
  type:     annotation
  prefix:   /

