app:
  resource: "@AppBundle/Controller/DefaultController.php"
  type:     annotation
printer:
  resource: "@AppBundle/Controller/PrinterController.php"
  type:     annotation
snapshot:
  resource: "@AppBundle/Controller/SnapshotController.php"
  type:     annotation

