parameters:
    voxelprinter.size: 12
    entity.image: "AppBundle:Image"

services:
  controller.printer:
    class: AppBundle\Controller\PrinterController
    arguments: ["@repository.printer"]
    calls:
      - [ setContainer, ["@service_container"] ]

  controller.snapshot:
    class: AppBundle\Controller\SnapshotController
    arguments: ["@repository.images"]
    calls:
      - [ setContainer, ["@service_container"] ]

  repository.printer:
    class: AppBundle\Repository\PrinterRepository
    arguments: ["@session"]

  repository.images:
    class: AppBundle\Repository\ImageRepository
    factory: ["@doctrine_mongodb", getRepository]
    arguments:
      - %entity.image%




